### ISSUE TITLE
About node encoding and decoding

### ISSUE THREAD

**Issue by icexin** [jrhy/mast#78]
How to implement `Marshal`  and  `Unmarshal` in `RemoteConfig` to serialize nodes more compactly? 

Thank you!

**Comment by jrhy** [comment]
Hi, thanks for the question! I added an example called [TestCustomMarshal](https://github.com/jrhy/mast/blob/e085b4595305b476454d9ff46c7663b859328eb5/lib_test.go#L900) in 1.1.3. You may also be interested in the use like [s3db does to setup `gob`](https://github.com/jrhy/s3db/blob/main/internal/crdt/crdt.go#L207). 

Please let me know if that helps. Cheers!

**Comment by icexin** [comment]
Thanks  for your reply. Gob is a more compact encoding format than JSON, but it is exclusive to go, which is not convenient for other languages to parse. In addition, it will add additional type information every time it is encoded. In fact, the type information of the codec involved in the mast code is determined, such as mastNode, so a schemaless codec will be more efficient. I will post a PR later to express my thoughts.
