### ISSUE TITLE
More flexible iteration API

### ISSUE THREAD

**Issue by jrhy** [jrhy/mast#83]
The great contribution in [issue 81](https://github.com/jrhy/mast/issues/81) got me thinking: At some point I think it will be nice to add `Min()`, `Max()`, `Floor()`, `Ceil()`, `Next()`, and `Prev()`, and be able to change the iteration order (start from high end of range).  I would welcome any opinions on this.  E.g. the proliferation of permutations in `Mast` method names (e.g. `DiffSeekIterReverse()`) could get kinda ugly, so maybe it would make sense to build a new `Cursor` struct to attach parameters/state.

**Comment by icexin** [comment]
A `cursor` or `iterator` api would be great. The iterator interface may add `First`, `Last`, `Seek`, `Next`, `Prev`, `Key`, `Value` and so on.

You can refer to the interface design of boltdb or leveldb 

https://pkg.go.dev/github.com/boltdb/bolt#Cursor
https://pkg.go.dev/github.com/syndtr/goleveldb@v1.0.0/leveldb/iterator#Iterator

**Comment by jrhy** [comment]
* 18ba6dad9d introduce Cursor for tree navigation with Forward, Backward, Min, Max, Ceil methods
* 409669286b add DiffCursor for iterative diffing without callbacks
